# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160726_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 26, 14, 29, 12, 19136, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
